# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('title', models.CharField(blank=True, default=b'', max_length=256, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 title')),
                ('h1', models.CharField(blank=True, default=b'', max_length=256, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 h1')),
                ('img', models.CharField(blank=True, default=b'', max_length=256, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0443')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_uuid_image, verbose_name='\u0421\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u043f\u0443\u0441\u043a\u0430')),
                ('celery_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='ID celery-\u0437\u0430\u0434\u0430\u0447\u0438')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
